<?php
/**
 * Implements hook_block_info().
 */
function m_blocks_block_info(){
  $blocks['logo_magisterio'] = array(
    'info' => t('Logo representativo de sección'), 
  );
  $blocks['site_logo'] = array(
    'info' => t('Logo configurado en el theme'), 
  );
  $blocks['sub_menu_interna'] = array(
    'info' => t('Sub menu de las páginas internas'), 
  );
  $blocks['magisterio_suscripcion'] = array(
    'info' => t('Bloque para crear suscripciones al sitio'), 
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function m_blocks_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'logo_magisterio':
      $block['content'] = _m_blocks_logo_page();
    break;
    case 'site_logo':
      $block['content'] = _m_blocks_site_logo();
    break;
    case 'sub_menu_interna':
      $block['content'] = _m_blocks_sub_menu_interna();
    break;
    case 'magisterio_suscripcion':
      $block['subject'] = '';
      $block['content'] = drupal_get_form('magisterio_suscripcion');
    break;
  } 
  return $block;
} 

function _m_blocks_logo_page(){
  global $base_url;
  $link = '';
  if (drupal_is_front_page()) $link = l('', $base_url);
  $output = '<div class="m-logoperpage">'.$link.'</div>';
  return $output;
}

function _m_blocks_site_logo(){
  global $base_url;
  $url_logo = theme_get_setting('logo');
  $variables_image = array(
    'path' => $url_logo,
    'title' => 'Home',
    'attributes' => array(),
  );
  $image_html = render(theme_image($variables_image));
  $output = '<a href="'.$base_url.'">' . $image_html . '</a>';
  return $output;
}

function _m_blocks_sub_menu_interna(){
  $url = request_path();
  $menu = menu_load_links('main-menu');
  $url_arr = explode('/', $url);
  if(count($url_arr) > 1) $url = $url_arr[0];
  switch ($url) {
    case 'editorial':
      $pathern = 466;
    break;
    case 'libreria':
      $pathern = 467;
    break;
    case 'revista':
      $pathern = 468;
    break;
    case 'formación':
      $pathern = 469;
    break;
    
    default:
      # code...
    break;
  }
  $sub_menu = array();
  foreach ($menu as $key => $value) {
    if($value['p1'] == $pathern && $value['depth'] == 2) {
      $title = $value['link_title'];
      $path = ($value['link_path'] == '<front>') ? '' : path_load($value['link_path']);
      $path = ($path == '') ? '' : $path['alias'];
      $sub_menu[] = l($title,$path);
    }
  }

  $list = array(
    'items' => $sub_menu,
    'title' => '',
    'type' => 'ul',
    'attributes' => array(),
  );
  return theme_item_list($list);
}


/**
 * Implements hook_form_alter().
 */
function m_blocks_form_alter(&$form, &$form_state, $form_id){
  switch ($form_id) {
    case 'user_login_block':
      $form['actions']['submit']['#value'] = t('Entrar');
    break;
  }
}


function magisterio_suscripcion($form, $form_state){
  $form['title'] = array(
    '#markup' => t('Recibe nuestras novedades'),
  );

  $form['mail'] = array(
    '#type' => 'textfield',
    '#title' => t('Digita tu correo'),
    '#attributes' => array(
      'id' => array('edit-mail'),
    ),
  );
  return $form;
}